name = "nameo-worker"
main = "backend/worker/index.js"
compatibility_date = "2024-01-01"

[vars]
# AUTH0_DOMAIN = "dev-17f30x2uvmivb8or.us.auth0.com"
# AUTH0_AUDIENCE = "https://nameo-api"
ORCHESTRATOR_URL = "https://nameo-search-worker.benjamin-f-mcdaniel.workers.dev"
ORCHESTRATOR_TOKEN = "dev-search-shared-secret"  # replace with a secret via CF dashboard for production

[[d1_databases]]
binding = "NAMEO_DB"                # used in Worker env.NAMEO_DB
database_name = "nameo-db"          # D1 database name in Cloudflare dashboard
database_id = "4afe937a-4c9b-4cb1-bfad-64d8844ca26e"